import type { Metadata } from 'next'
import * as React from 'react';
import './globals.css'
import { ThemeProvider } from './providers'
import { Toggle } from '../components/ui/toggle';
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'FL150 App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="flex min-h-screen flex-col">
        <ThemeProvider attribute="class" defaultTheme="light" disableTransitionOnChange>
          <header className="fixed top-0 left-0 right-0 justify-between h-16 flex items-center px-4 z-50 shadow bg-white dark:bg-black">
            <Link href="/">Home</Link>
            <Toggle />
          </header>
          {/* Page Content */}
          {children}
          <footer className="text-center py-4">
            Fl150 LLC.</footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
